<?php

use Illuminate\Database\Seeder;

class MigrationToVPSPortfolioItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('portfolio_items')->delete();
        
        \DB::table('portfolio_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Como crear un cliente',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/URdL0FnUCEPRMjJoi0kZtQaJrUfW153tVaaCfVHt.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=DSiuOglOcOM&list=PLAW4Lyi4HFiu6kHp0sxM72EKejYTauzZW&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => 'Ver Video',
                'button_icon' => 'fas fa-align-center',
                'link' => 'https://www.youtube.com/watch?v=DSiuOglOcOM&list=PLAW4Lyi4HFiu6kHp0sxM72EKejYTauzZW&index=4',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Que es el CRM y como utilizarlo',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/v9Q84L7GcJJcWL0qKFMxCIIGBqtWHL0mdqEnz8lA.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=LxQu0niSQ1k&list=PLAW4Lyi4HFiu6kHp0sxM72EKejYTauzZW',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Que es el reporte de documentos no aplicados',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/C9N62IXZu1EmCPcrogLfDqXhNHSoW02ZXebyl4QZ.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=JahoVm1O_lw&list=PLAW4Lyi4HFiu6kHp0sxM72EKejYTauzZW&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Como imprimir un reporte de cuentas por cobrar',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/x7QUuGqLKn9Sdeng0rIYg89Re2qWhHF9sOPrsJwS.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=Rj_ejNHtSNA&list=PLAW4Lyi4HFiu6kHp0sxM72EKejYTauzZW&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Que son productos, subproductos e insumos',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/WFIcPM7UcT3UvYVSHQe43O3Mmacq65gGiS6D3g7v.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=E5Ioa7_WyuM&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Como crear un producto',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/dcUkk3hYZaZ0Zb0U3NOm68NYFftnPjU6Yjsckp5M.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=AWUpfLOc2_I&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Como crear un subproducto',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/DCLj7IVIMAEYEiQzAU5SyqMnSPxBNNzTYQP16YMj.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=vdBAtMGRNkQ&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Como crear un insumo',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/xNn3MJyLnltkitntjBBCS3wXL4mJI6KsjRIuNYwE.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=WuIDnqoSwlg&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=7',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Como crear un articulo para la venta',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/SgPw2aJ5EOhTU9RLFlLnPDFJYiUHQLHdn4zlPodq.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=tvjv-4lWj2Y&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=5',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Como activar o desactivar un articulo para la venta',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/K3UGzJAA0MaPYpZXKdVn2Em0WSCl23E1LaVZ7fRM.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=JHQXhiA0k8w&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=6',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Como especificar maximos y minimos de inventarios',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/VeN9x0Oqqgx6ZOa47NgF17hMLlpAx6U5aWR2HoiX.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=x-WZTNhfRPc&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=8',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Como hacer un reporte de inventario fisico',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/K4CUztvxEEcylgr0XdxazKNwmjqbR4AvBtKpNjUi.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=UETN-tYg1nM&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=9',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Como añadir formula de desgloce a un producto',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/oUlAUIQSQUER4HEACEedD3Am80vb2tUxcWQKayyF.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=HJ0ZBRRZTs0&list=PLAW4Lyi4HFissWjGi_kLNvhnPm9Jdi5To&index=1',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => '2020-06-03 21:09:48',
                'created_at' => NULL,
                'updated_at' => '2020-06-03 21:09:48',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Que son otras cuentas por pagar',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/7gF2oVwm3w9dtbMxpScLdAg4uE1pr8C5ZMvFTowN.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=N5oxHGUwU1A&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Como digitar una factura por pagar',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/7xpC2eiJpoNOhOafACNB8qN65HV5B6N95JPkRKZY.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=Zqh3IXJHQxs&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Como generar una factura de suplidor informal',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/r01GrsHOU0rNjbszrP6WBWEXSsvtdoYwPCULXc61.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=DJbc7TuYL1w&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=1',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'como crear un cheque',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/A4rWOqOqsnPfdffs3O0XZpL3yjyt0EjslDkl1LuF.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=lwcuhcNwjvs&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Como asignar un cheque a varias facturas',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/wE0A2HlJDf6Bu7DomPtmbbq90vmkcQtMMrYmZMtg.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=9_CYd0XSN_w&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=5',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Como crear una cuenta bancaria',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/2zYgUbWRAyStcvfMHuVsaXxdCGQZTfbkYOSNXoLF.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=SFQKYoyq3xU&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=6',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Como realizar una conciliacion bancaria',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/SdArYEmUhP34eVBWIPBO6ZBilZx5dJLOPCJhMnW2.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=sMMeby82dkg&list=PLAW4Lyi4HFitiFZPA3eNkY9WUGzy2IgJc&index=7',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Como dolarizar el sistema',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/Ckodnde1rFXFj7SNCQUKJ2bmD48TKs73Ql6MhXUW.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=QbB4fetYBuo',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Como hacer el 606',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/ve32MkJY1Y3kXrAr94zK8Pbr8lWWMK3n5YJnL8gh.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=FnrjDi5O_GM&list=PLAW4Lyi4HFisCGefj7AQRwwVDqwXj7w5u',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Como hacer una orden de compra',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/7b69H3Pkxxvs45hLr5GRCxfmVbFrOhB2IafKN9v1.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=h8NT-E60sa0&list=PLAW4Lyi4HFisCGefj7AQRwwVDqwXj7w5u&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Como recibir una orden de compra',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/0BtzBng7AdT6Z5IcwN4QBxATbaCNr2zbBn3xT8sI.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=7aC-Fi-1Fmw&list=PLAW4Lyi4HFisCGefj7AQRwwVDqwXj7w5u&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Como hacer una liquidacion aduanal',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/elcWoSDeMNL3581UlZeyJlXkHx7nuxwbMqGr1qc0.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=ckmB_0Jxq7U&list=PLAW4Lyi4HFisCGefj7AQRwwVDqwXj7w5u&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Como generar una orden de produccion',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/4tltqDcoVXMpqIeXPfNl4s03AefVt7zwohiNIXpd.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=YsN_TtuQkbM&list=PLAW4Lyi4HFiseW-IYa0DaMTsMPg4ImiuU&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Como imprimir un desgloce de produccion',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/OWV9VBn1KYN8L5Ck2TXOYOabmctgWUJp06r2Ulx3.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=26ft4k1RFts&list=PLAW4Lyi4HFiseW-IYa0DaMTsMPg4ImiuU&index=1',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Introduccion al modulo de caja',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/uosGuJMpN4XblBrVwK5T183BGQhqPO8DlRHK2qMt.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=rjf-qdOtf3I&list=PLAW4Lyi4HFisSfON_C5zsVwttMP46sjKl',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Como crear una factura de contado',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/Z0qfHqxZp9LeRia1gAFfcSefrSENGTuBpJQ2luIc.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=0T2QP9VI_xM&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Como crear una factura a credito',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/KGRFeFwYmUYyI27Pilm5pQSF5ann8zbLab3WJLl0.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=AEgVgrJYQvU&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Como crear un recibo de ingresos de factura',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/M7cwJDhSkn7jssUSyoFxWitDxefNHU6yQ95KfA0Q.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=LUBpUHH0CkI&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Como anular una factura',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/3JIGXqCJPt4rkYlnb8gYA0XhUch2TGLMrFuAJpcU.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=MH5uKTJpSuI&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=1',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Como crear un recibo de ingresos de varios',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/rBgKYnU0WeRbgUhXl28publEH3FmL3FEHghPXnBD.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=LHI6KpMKPqY&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=7',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Como convertir un recibo a varios',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/SkIcCsUR3B2LWWf6r2PeIEel5fR0q4uXUihI1mY7.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=MIgsLdW7B1M&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=8',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Como crear una nota de credito',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/rOZIxiwSydwTigbpMJ9fEsGmObksP9gcfzankVuy.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=TpxtEpYaRNE&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=6',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Como crear una nota de debito',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/0B0o01CCZddG9pYcVp9W77hO7TKZskhu9pCDRTfO.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=IubefpBcGpc&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=10',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Como hacer el 607',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/26zyJldOknoZ6wZ2Ju9VSkbMGpK9hbaRmllokg1C.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=8cUYGrt9FDM&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=11',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Como cambiar la fecha a una factura',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/aWUB5ElSLwMKDnZ8Wf5qWb56wWsTufbRSRBvC8pd.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=i3MjYwBtGaQ&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=5',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Como realizar un reporte comparativo de ventas y compras',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/mDJNaH0pTtYq6kUg9s4nOKxGwW1HYSQAQnvNsLYd.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=Hl5FwJ2Vrfs&list=PLAW4Lyi4HFivXgJksbaemit4uIFyLrsVr&index=12',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Como crear una cotizacion',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/mtiBE9QTXArJdA6NcRHvNwXhOKrkhWM6qZkGTJoV.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=LBYXOtRQyX0&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Como desglozar una cotizacion',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/yvburcWSkzTsZQxVbf6VUs9kdQCSkjuNITI8rdIn.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=m0vuKpn77e8&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'Como reailzar un analisis de costo',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/7Ssn2GB6o2njhrP8UcsEVP8u2fEOpOvWQF5vDuKi.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=22XqXotmyLc&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'Como aplicar un descuento',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/ZI5WcDeBmIpdDusURzmhdympe1r03s2NlaDtVrNh.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=9q6myRlz8dU&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX&index=5',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Como cambiar un precio',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/y6wwVdwtHBFbsH4PGX7tiPjxnjRXXyoaPOYbXzDJ.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=kNzYYy-FTHQ&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Como aplicar gastos de transporte e instalacion',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/HEYRKGoVz2Qn7jBDP5H9tB25D94DxL7QjBErhK6M.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=FnlEZtxX7ec&list=PLAW4Lyi4HFis9PW26FAWbQkYcagKNwkvX&index=6',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Como configurar los procesos contables',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/mum41cpSTA9PZr1pd7kB9CPN5QBgAEH2RZnlVx2G.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=L777LtWr3-g&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Como consultar el libro diario',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/QFdtvOWC269DodbYkUzRTTLjQQ6SqaKyImRBNSsc.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=wpfK8LQ-l7A&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=2',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Como eliminar asientos contables',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/uCcO8bR2HwhJLBBIelt97LAFbLhYHWgb87TlCyab.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=w66on-Jb39I&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=3',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Como consultar el libro mayor',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/90PaHqxMoPIJn119Jz6ZgKH1yi8hGeI71BJZQcL7.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=ZOkj5dwc1bE&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=4',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Como imprimir estados financieros',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/hHT6NsHebbzxzs6GOycBur5jVfh3IoUpD4tE1Onq.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=QAh1K-Y95Yw&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=5',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Como corregir asientos contables',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/dvNiuxNsPNPyd9krLubmOftLZtYsqwsM3q828jHz.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=AIDjXfkOPls&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=6',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Como hacer un asiento',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/5JOAPV3jYCyksFZYB4yaGxX8PhBIJUKxiNuQcxqb.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=ssGdgloHZbA&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=7',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Como introducir el catalogo de cuenta',
                'subtitle' => NULL,
                'logo' => 'content/portfolio/NwymNn1VaEAPcOLl3XqTjTM0HVPL0W7Z1yjNkMhR.png',
                'logo_link' => 1,
                'logo_link_type' => 0,
                'logo_link_address' => 'https://www.youtube.com/watch?v=o3WJ7LnbWVc&list=PLAW4Lyi4HFiuiK6burAda5F5lURPMLXJW&index=8',
                'screenshot' => NULL,
                'contenido' => NULL,
                'author' => NULL,
                'author_bio' => NULL,
                'link_title' => NULL,
                'button_text' => NULL,
                'button_icon' => NULL,
                'link' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}